#!/usr/bin/env bash
# sends a file from client to server
# accepts 4 parameters: 
#+	path to file to be transferred
#+	IP of the server receiving the file
#+	username scp connects with
#+	path to the SSH private key that scp uses

if [ $# -lt 5 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -i "$5" "$2" "$4"@"$3":~/
fi
