#!/usr/bin/env bash
# sends a file from client to server
# accepts 4 parameters: 
#+	path to file to be transferred
#+	IP of the server receiving the file
#+	username scp connects with
#+	path to the SSH private key that scp uses

if [ $# -lt 3 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit
fi
if [ $# -gt 3 ]
then
	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
else
	scp -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/
fi
