#!/usr/bin/env bash
# configure nginx /redirect_me to redirect to another page
apt-get -y update
apt-get -y install nginx
ufw allow 'nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
str="/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sed -i "/listen 80 default server/a \trewrite $str" /etc/nginx/sites-available/default
service nginx restart
