#!/usr/bin/env bash
# configure nginx for 404 - Not found
apt-get -y update
apt-get -y install nginx
ufw allow 'nginx HTTP'
echo "Hello World!" |sudo tee /var/www/html/index.html > /dev/null
str="^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sed -i "46i rewrite $str" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null
sed -i "46i error_page 404 /custom_404.html;" /etc/nginx/sites-available/default
service nginx restart
