#!/usr/bin/env bash
# configure nginx with custom header in web-01 and web-02

apt-get -y update
apt-get -y install nginx
ufw allow 'nginx HTTP'
echo -e "Hello World!" > /var/www/html/index.html
str="^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sed -i "46i rewrite $str" /etc/nginx/sites-available/default
echo -e "Ceci n'est pas une page" > /var/www/html/custom_404.html
sed -i "46i error_page 404 /custom_404.html;" /etc/nginx/sites-available/default
sed -i "46i add_header X-Served-By: $hostname always" /etc/nginx/sites-available/default 
service nginx restart
