#!/usr/bin/env bash
# Install and Configure HAproxy on a server for loadbalancing
#
balancer="\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers
    
backend webservers
    balance roundrobin
    server 26071-web-01 54.197.106.207:80 check
    server 26071-web-02 54.82.183.113:80 check
"
# Update packages
apt-get -y update
apt-get -y upgrade

# Add HAProxy PPA
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.6
apt-get -y update

# Install HAProxy
apt-get -y install haproxy
cp -a /etc/haproxy/haproxy.cfg{,.bak}
echo "$balancer" >> /etc/haproxy/haproxy.cfg
service haproxy restart