#!/usr/bin/env bash                                                 
# configures Nginx to listen on port 80 of all server's active IPv4 IPs                                                                 
sed -i "s/8080/80/g" /etc/nginx/sites-available/default             
rm /etc/nginx/sites-enabled/default                                 
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default                                                               
service nginx start
