#!/usrbin/env bash
# configures the container to run as the nginx user and listen on 8080 port
sed -i "s/#user www-data/user nginx" /etc/nginx/nginx-conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
pkill apache2
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx start